global.API_KEY = ''; // nomics api key
global.API_URL = 'https://api.nomics.com/v1/currencies/ticker';
global.EOS_PROTOCOL = 'https';
global.EOS_HOST = 'eu.eosdac.io';
global.EOS_PORT = '443';
global.EOS_KEY = '';  // private key to publish feed
global.EOS_CHAIN = 'aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906';
global.ORACLE = "eosdacserver";
global.CONTRACT = "delphioracle";
global.FREQ = 60 * 2 * 1000;
global.ORACLE_PERMISSION = "oracle";
global.CURRENCIES = ['USD'];
